"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.API_ROUTES = exports.SOCKET_EVENTS = void 0;
exports.SOCKET_EVENTS = {
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
    MESSAGE_SEND: 'message:send',
    MESSAGE_RECEIVE: 'message:receive',
    TYPING_START: 'typing:start',
    TYPING_STOP: 'typing:stop',
    ROOM_JOIN: 'room:join',
    ROOM_LEAVE: 'room:leave',
    ROOM_UPDATE: 'room:update',
    // Notification gateway events
    NOTIFICATION_NEW: 'notification:new',
    NOTIFICATION_UNREAD: 'notification:unread',
    NOTIFICATION_SUBSCRIBE: 'notification:subscribe',
    NOTIFICATION_ANSWER: 'notification:answer',
    NOTIFICATION_READ: 'notification:read',
    // Room gateway events
    ROOM_SUBSCRIBE: 'room:subscribe',
    ROOM_UNSUBSCRIBE: 'room:unsubscribe',
    ROOM_CREATED: 'room:created',
    ROOM_UPDATED: 'room:updated',
    ROOM_LAST_MESSAGE_UPDATED: 'room:last-message-updated',
    ROOM_DELETED: 'room:deleted',
    ROOM_INVITED: 'room:invited',
    MEMBER_JOINED: 'member:joined',
    MEMBER_INVITED: 'member:invited',
    MEMBER_LEFT: 'member:left',
    MEMBER_KICKED: 'member:kicked',
    MEMBER_ROLE_UPDATED: 'member:role_updated',
    AVAILABILITY_CREATED: 'availability:created',
    AVAILABILITY_UPDATED: 'availability:updated',
    AVAILABILITY_DELETED: 'availability:deleted',
    PROPOSAL_CREATED: 'proposal:created',
    PROPOSAL_UPDATED: 'proposal:updated',
    PROPOSAL_DELETED: 'proposal:deleted',
    PROPOSAL_SELECTED: 'proposal:selected',
    VOTE_CREATED: 'vote:created',
    VOTE_UPDATED: 'vote:updated',
    VOTE_DELETED: 'vote:deleted',
    ACTIVITY_CREATED: 'activity:created',
    ACTIVITY_UPDATED: 'activity:updated',
    ACTIVITY_DELETED: 'activity:deleted',
    USER_ONLINE: 'user:online',
    USER_OFFLINE: 'user:offline',
    NOTIFICATION: 'notification',
};
exports.API_ROUTES = {
    AUTH: {
        REGISTER: '/auth/register',
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
        GOOGLE: '/auth/google',
        GITHUB: '/auth/github',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
    },
    USERS: {
        ME: '/users/me',
        SEARCH: (query) => `/users/search?query=${query}`,
        GET: (id) => `/users/${id}`,
        UPDATE: (id) => `/users/${id}`,
        ROOMS: (id) => `/users/${id}/rooms`,
        FRIENDS: (id) => `/users/${id}/friends`,
    },
    FRIENDS: {
        REQUESTS: '/friends/request',
        RELATIONS: '/friends/relations',
        SEND: (userId) => `/friends/request/${userId}`,
        ACCEPT: (friendshipId) => `/friends/accept/${friendshipId}`,
        REJECT: (friendshipId) => `/friends/reject/${friendshipId}`,
        DELETE: (friendshipId) => `/friends/${friendshipId}`,
        BLOCK: (friendshipId) => `/friends/block/${friendshipId}`,
        UNBLOCK: (friendshipId) => `/friends/unblock/${friendshipId}`,
    },
    ROOMS: {
        CREATE: '/rooms',
        GET: (id) => `/rooms/${id}`,
        UPDATE: (id) => `/rooms/${id}`,
        DELETE: (id) => `/rooms/${id}`,
        JOIN: (id) => `/rooms/${id}/join`,
        LEAVE: (id) => `/rooms/${id}/leave`,
        MEMBERS: (id) => `/rooms/${id}/members`,
        UPDATE_ROLE: (roomId, userId) => `/rooms/${roomId}/members/${userId}/role`,
        KICK: (roomId, userId) => `/rooms/${roomId}/members/${userId}`,
    },
    AVAILABILITY: {
        LIST: (roomId) => `/rooms/${roomId}/availability`,
        CREATE: (roomId) => `/rooms/${roomId}/availability`,
        UPDATE: (roomId, id) => `/rooms/${roomId}/availability/${id}`,
        DELETE: (roomId, id) => `/rooms/${roomId}/availability/${id}`,
        MATCHING_DATE: (roomId) => `/rooms/${roomId}/matchingDate`,
    },
    PROPOSALS: {
        LIST: (roomId) => `/rooms/${roomId}/proposals`,
        CREATE: (roomId) => `/rooms/${roomId}/proposals`,
        UPDATE: (roomId, id) => `/rooms/${roomId}/proposals/${id}`,
        DELETE: (roomId, id) => `/rooms/${roomId}/proposals/${id}`,
        SELECT: (roomId, id) => `/rooms/${roomId}/proposals/${id}/select`,
    },
    VOTES: {
        LIST: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/votes`,
        VOTE: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/vote`,
        UPDATE: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/vote`,
        DELETE: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/vote`,
    },
    ACTIVITIES: {
        LIST: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/activities`,
        CREATE: (roomId, proposalId) => `/rooms/${roomId}/proposals/${proposalId}/activities`,
        UPDATE: (roomId, proposalId, id) => `/rooms/${roomId}/proposals/${proposalId}/activities/${id}`,
        DELETE: (roomId, proposalId, id) => `/rooms/${roomId}/proposals/${proposalId}/activities/${id}`,
    },
    MESSAGES: {
        LIST: (roomId) => `/rooms/${roomId}/messages`,
        CREATE: (roomId) => `/rooms/${roomId}/messages`,
        DELETE: (roomId, id) => `/rooms/${roomId}/messages/${id}`,
    },
    STORAGE: {
        REMOVE: {
            PROFILE_PICTURE: '/storage/remove/profile-picture',
        },
        UPLOAD: {
            PROFILE_PICTURE: '/storage/upload/profile-picture',
            ROOM_IMAGE: '/storage/upload/room-image',
            MESSAGE_ATTACHMENT: '/storage/upload/message-attachment',
        },
    },
};
